SELECT
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT os.USER_ID) / total.total_users,
        1
    ) AS PURCHASED_RATIO
FROM ONLINE_SALE os
JOIN USER_INFO ui
    ON os.USER_ID = ui.USER_ID
JOIN (
    SELECT COUNT(*) AS total_users
    FROM USER_INFO
    WHERE JOINED >= '2021-01-01'
      AND JOINED < '2022-01-01'
) total
WHERE ui.JOINED >= '2021-01-01'
  AND ui.JOINED < '2022-01-01'
GROUP BY
    YEAR(os.SALES_DATE),
    MONTH(os.SALES_DATE)
ORDER BY
    YEAR,
    MONTH;
