WITH G AS (
    SELECT 
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
),
RANKED AS (
    SELECT 
        G.SCORE,
        E.EMP_NO,
        E.EMP_NAME,
        E.POSITION,
        E.EMAIL,
        RANK() OVER (ORDER BY G.SCORE DESC) AS RN
    FROM G
    JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
)
SELECT 
    SCORE,
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM RANKED
WHERE RN = 1;
